#!/system/bin/sh

export USER=u0_a485 #run whoami in termux

### Setup env ###

export SHELL=/data/data/com.termux/files/usr/bin/bash
export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
export BOOTCLASSPATH=/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/syst>export PATH=/data/data/com.termux/files/usr/bin
export TMPDIR=/data/local/nhsystem/kali-arm64/tmp
export HOME=/data/local/nhsystem/kali-arm64/root

### Run termux-x11 ###

echo "DISPLAY="$1
/data/data/com.termux/files/usr/bin/pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 & > /dev/null

echo "PulseAudio started"
/data/data/com.termux/files/usr/bin/termux-x11 $1 &
X11_PID=$!
echo "Termux-x11 started"

### Exit Termux-x11 and Pulseaudio

echo "Press any key to terminate"
while true; do
read -rsn1 key  # Read a single character silently
if [[ -n "$key" ]]; then
kill $X11_PID
pkill pulseaudio
break  # Exit the loop if a key is pressed
fi
done
